version: '1.4.0.{build}'
image: Visual Studio 2019

configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  nuget restore SevenZip.sln

environment:
  COVERALLS_REPO_TOKEN:  
    secure: c5HtM5NVjJZQ4gbujqELYPgeCHTr9UMpuYl/A4MYX0lSdsMh/QISCfZxUHuLszPI

build:
  parallel: true
  project: 'SevenZip.sln'
  publish_nuget: false

after_build:
  - cmd: nuget pack package.nuspec -version "%APPVEYOR_BUILD_VERSION%"

test_script:
- ps: Invoke-Expression ($env:USERPROFILE + '\.nuget\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe -register:Path64 -filter:"+[*]* -[SevenZip.Tests]* -[nunit.framework]*" -target:"' + $env:USERPROFILE + '\.nuget\packages\nunit.consolerunner\3.10.0\tools\nunit3-console.exe" -targetargs:"/domain:single Stage/Release/net45/SevenZip.Tests.dll" -output:coverage.xml')
- ps: Invoke-Expression 'dotnet new tool-manifest'
- ps: Invoke-Expression 'dotnet tool install coveralls.net'
- ps: Invoke-Expression 'dotnet tool restore'
- ps: Invoke-Expression 'dotnet tool run csmacnz.Coveralls --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor'

artifacts:
  - path: 'Squid-Box.SevenZip*.nupkg'
    name: 'NuGet'

  - path: 'coverage.xml'
    name: 'Code Coverage'

deploy:
  - provider: NuGet
    api_key:
      secure: QHcRI5K4Gls/HtuXas7mofJp3/UIexnWnGeXch3+btMTwTk4mgvsWDWPcZWXor9y
    artifact: /SevenZip.*\.nupkg/
    skip_symbols: false
    on:
      branch: master
