version: '1.1.{build}.0'
image: Visual Studio 2017

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore SevenZip.sln

build:
  parallel: true
  project: 'SevenZip.sln'
  publish_nuget: true

after_build:
  - cmd: nuget pack package.nuspec -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
  path: 'Squid-Box.SevenZip*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: AWbl6aAa09NxVWFo9EDRC12RhY090havc8aWB9j0S4crFvICIkIvON0gUxG2q8QZ
  artifact: /SevenZip.*\.nupkg/
  skip_symbols: false
  on:
    branch: master
