on:
  push:
    branches: [ "master" ]

env:
  VERSION: '1.5.1.${{ $github.run_id }}'

jobs:
  build:
      
    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
 
    - name: Compile solution
      run: |
        dotnet build -c Release /p:AssemblyVersion={{ $VERSION }} /p:Version={{ $VERSION }}
        dotnet build -c LiteRelease /p:AssemblyVersion={{ $VERSION }} /p:Version={{ $VERSION }}
      
    - name: Pack NuGets
      run: |
        nuget pack package.regular.nuspec -p:PackageVersion={{ $VERSION }}
        nuget pack package.lite.nuspec -p:PackageVersion={{ $VERSION }}

    - name: Push NuGet packages
      run: dotnet nuget push Squid-Box.SevenZip*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}